# Generated by Django 6.0.5 on 2026-05-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_hours', models.FloatField()),
                ('attendance', models.FloatField()),
                ('previous_marks', models.FloatField()),
                ('assignment_score', models.FloatField()),
                ('prediction', models.CharField(max_length=20)),
                ('probablity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
