# Generated by Django 6.0.5 on 2026-05-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionhistory',
            old_name='probablity',
            new_name='probability',
        ),
    ]
